---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manifestation.pez.sh
  resources:
  - desires
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manifestation.pez.sh
  resources:
  - desires/finalizers
  verbs:
  - update
- apiGroups:
  - manifestation.pez.sh
  resources:
  - desires/status
  verbs:
  - get
  - patch
  - update
